[package]
name = "computer_science_problems_in_rust"
version = "0.1.0"
authors = ["Jabbslad <jabbslad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"